// Writes migrations/0002_seed.sql from data/library.json (the built-in catalogue).
// Usage: node scripts/seed-sql.mjs && npx wrangler d1 execute monge --remote --file migrations/0002_seed.sql
import { readFileSync, writeFileSync } from 'node:fs';

const items = JSON.parse(readFileSync(new URL('../data/library.json', import.meta.url), 'utf8'));
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = ['-- Generated by scripts/seed-sql.mjs from data/library.json — do not edit by hand.'];
items.forEach((item, i) => {
  lines.push(
    `INSERT INTO items (slug, category, data, published, sort, updated_at) VALUES (${q(item.slug)}, ${q(item.category)}, ${q(JSON.stringify(item))}, 1, ${(i + 1) * 10}, ${q(item.updated)})\n` +
      `  ON CONFLICT(slug) DO UPDATE SET category = excluded.category, data = excluded.data, sort = excluded.sort, updated_at = excluded.updated_at;`,
  );
});
writeFileSync(new URL('../migrations/0002_seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log(`migrations/0002_seed.sql: ${items.length} items`);
