import type { Dict } from '@/lib/i18n';

export const en: Dict = {
  meta: {
    title: 'Monge — precise AI CAD for equipment manufacturers',
    shortTitle: 'Monge',
    description:
      'Monge builds precise 3D models of stainless steel equipment from dimensions or a drawing: tables, sinks, shelving, chambers. Its own B-Rep kernel, an AI designer, STEP for production and a cloud model library.',
  },
  nav: {
    product: 'Product',
    library: 'Library',
    pricing: 'Pricing',
    download: 'Download',
    contact: 'Contact',
    cta: 'Early access',
    menu: 'Menu',
    close: 'Close',
    language: 'Language',
  },
  hero: {
    badge: 'Monge 0.3 — beta for macOS',
    titleA: 'From dimensions',
    titleB: 'to production',
    titleC: 'in minutes',
    lead:
      'AI-powered CAD for food-service equipment makers. Describe a table, a sink or a chamber — Monge builds a precise model and prepares the files for your shop floor and a render for your client.',
    primary: 'Get early access',
    secondary: 'Browse the library',
    note: 'Pilot factories get 3 months free',
    viewerLabel: 'Live model from Monge',
    stats: [
      { value: 'B-Rep', label: 'exact geometry, not a triangle mesh' },
      { value: '~1.5 s', label: 'to rebuild a 530-face wheel' },
      { value: 'STEP', label: 'export for any CAD system and CNC' },
    ],
  },
  marquee: ['Work tables', 'Sinks', 'Shelving', 'Trolleys', 'Extraction hoods', 'Smoking chambers', 'Cold rooms', 'Spare parts and bushings', 'Turned parts'],
  pain: {
    eyebrow: 'The problem',
    title: 'Every custom order means hours of redrawing',
    lead:
      'The client needs a 1730 mm table, not a 1500 mm one. The designer opens CAD again, moves dimensions, rebuilds flat patterns, counts tubing and renders a picture for the quote. On every single order.',
    before: 'Today',
    after: 'With Monge',
    beforeItems: ['Redrawing the product by hand', 'Flat patterns and nesting done separately', 'Quotes without a visual', 'Expensive licences for every seat'],
    afterItems: ['Dimensions in words or a form', 'Model and files rebuild themselves', 'A photoreal render right away', 'A subscription for the price of a lunch'],
  },
  how: {
    eyebrow: 'How it works',
    title: 'Four steps from request to shop floor',
    steps: [
      { title: 'Describe the product', text: 'With dimensions in a form or in a sentence: “wall table 1500×600×850, 50 mm upstand, bottom shelf”.' },
      { title: 'AI builds the model', text: 'Monge assembles it on its own exact kernel: real planes, cylinders and fillets.' },
      { title: 'Adjust the dimensions', text: 'Change any parameter — the model rebuilds in seconds and keeps its feature history.' },
      { title: 'Send it to production', text: 'STEP for the designer and CNC, a render for the sales quote.' },
    ],
  },
  features: {
    eyebrow: 'Capabilities',
    title: 'An engineer’s tool, not a toy',
    soon: 'in development',
    items: [
      { key: 'kernel', title: 'Its own exact kernel', text: 'B-Rep geometry written in Rust: planes, cylinders, tori, NURBS. No third-party kernels, no licence fees.', soon: false },
      { key: 'ai', title: 'AI designer', text: 'Models are built from a description or a drawing: the AI drives Monge and dimensions parts like an engineer.', soon: false },
      { key: 'history', title: 'Parameters and history', text: 'Sketch → part → assembly. Change a dimension and everything recalculates; a failed step rolls back by itself.', soon: false },
      { key: 'render', title: 'Renders for quotes', text: 'A built-in ray-traced renderer: a picture for your quote straight from the model.', soon: false },
      { key: 'sheet', title: 'Flat patterns and nesting', text: 'Sheet metal with bends, unfolding with your press brake’s K-factor, DXF for laser cutting, tube cut lists.', soon: true },
      { key: 'cloud', title: 'Cloud library', text: 'Ready-made products: view them in 3D in the browser and download production files.', soon: false },
    ],
  },
  showcase: {
    eyebrow: 'Proven on the hard stuff',
    title: 'A 7J×17 wheel from the factory drawing',
    text: 'To test the kernel we built a cast alloy wheel from the manufacturer’s drawing: 20 windows, bolt pockets, fillets and a dished face. Exact geometry, 530 faces, a solid with zero errors.',
    facts: [
      { value: '530', label: 'B-Rep faces' },
      { value: '20', label: 'windows from the drawing' },
      { value: '0', label: 'topology errors' },
    ],
    cta: 'Open the model',
  },
  story: {
    eyebrow: 'Why Monge',
    title: 'Named after Gaspard Monge, the father of technical drawing',
    items: [
      { year: 'c. 300 BC', name: 'Euclid', text: 'Geometry as a system' },
      { year: '1637', name: 'Descartes', text: 'Coordinates: shape becomes number' },
      { year: '1799', name: 'Monge', text: 'Descriptive geometry — the language of drawings' },
      { year: '2026', name: 'Monge', text: 'Drawings built by AI' },
    ],
  },
  libraryPreview: {
    eyebrow: 'Library',
    title: 'Models ready for production',
    lead: 'View products in 3D right in your browser. Production files are available to Monge subscribers.',
    cta: 'Full library',
  },
  status: {
    eyebrow: 'Honest status',
    title: 'What works today and what we are building',
    doneTitle: 'Works',
    nextTitle: 'In development',
    done: ['Exact kernel: revolve, extrude, cuts, fillets', 'Parametric feature history', 'Assemblies and mates', 'STEP, STL, 3MF export', 'Ray-traced rendering', 'AI control of the model'],
    next: ['Sheet metal and DXF flat patterns', 'Tube frames', 'Bill of materials and nesting', 'Windows version', 'Configure products in the browser'],
  },
  pricing: {
    eyebrow: 'Pricing',
    title: 'A simple subscription, no annual contracts',
    lead: 'Pay monthly, cancel any time. Prices exclude VAT.',
    popular: 'Most popular',
    perMonth: '/ mo',
    plans: [
      { id: 'free', name: 'Start', price: '€0', desc: 'Get to know Monge', features: ['Library and 3D viewer in the browser', 'The app in viewer mode', 'News and updates'], cta: 'Start for free', highlight: false },
      { id: 'pro', name: 'Pro', price: '€49', desc: 'For a designer', features: ['All product templates', 'AI designer', 'STEP, STL, 3MF export', 'Renders for quotes', 'Production files from the library'], cta: 'Early access', highlight: true },
      { id: 'factory', name: 'Factory', price: '€149', desc: 'For a shop with up to 3 seats', features: ['Everything in Pro', 'Your templates and standards', 'Your logo on quotes', 'Shared shop library', 'Priority support'], cta: 'Become a pilot', highlight: false },
    ],
    custom: { title: 'Custom models', text: 'We turn your drawings into parametric Monge templates. From €100 per product.', cta: 'Discuss a project' },
    note: 'Monge is in beta, so subscriptions are by invitation. Leave a request — pilot factories get 3 months free.',
  },
  faq: {
    eyebrow: 'Questions',
    title: 'Frequently asked questions',
    items: [
      { q: 'Does Monge run on Windows?', a: 'Today Monge runs on macOS with Apple Silicon (M1–M4). A Windows version is in development — leave a request and we will tell you when it launches.' },
      { q: 'Will the files open in SolidWorks, Fusion or FreeCAD?', a: 'Monge exports STEP, the standard exchange format for exact geometry that all major CAD systems read.' },
      { q: 'Where are my models stored?', a: 'Models are built and stored on your computer. Only what you publish to the library goes to the cloud.' },
      { q: 'Do I need an internet connection?', a: 'Not for modelling. You need it for the library, the AI designer and the subscription check.' },
      { q: 'How do I become a pilot factory?', a: 'Leave a request describing your products. We will build templates of your typical products and give you 3 months free in exchange for feedback.' },
    ],
  },
  cta: {
    title: 'Let’s build your first table together',
    text: 'Tell us what you make. We will show you Monge on your own products.',
  },
  form: {
    name: 'Name',
    email: 'Email',
    company: 'Company',
    message: 'What do you make?',
    messagePlaceholder: 'E.g.: AISI 304 tables and sinks, 20–40 orders a month',
    kind: 'I’m interested in',
    kinds: { early_access: 'Early access', pilot: 'Factory pilot', custom: 'Custom models', other: 'Something else' },
    submit: 'Send request',
    sending: 'Sending…',
    success: 'Thank you! We got your request and will reply within 1–2 business days.',
    error: 'Could not send. Please try again in a moment.',
    consent: 'By sending this form you accept the',
    privacy: 'privacy policy',
  },
  library: {
    title: 'Model library',
    lead: 'Products and parts built in Monge. Spin them in 3D in your browser; production files come with Pro.',
    all: 'All',
    categories: { stainless: 'Stainless steel', precision: 'Precision parts', fasteners: 'Fasteners' },
    soonTitle: 'Coming to the library',
    soon: ['Sinks', 'Shelving', 'Trolleys', 'Hoods', 'Chambers'],
    empty: 'No models in this category yet.',
    open: 'Open',
    formats: 'Formats',
  },
  item: {
    back: 'Library',
    viewerHint: 'Drag to rotate, scroll or pinch to zoom',
    loading: 'Loading the model…',
    noWebgl: 'Your browser does not support 3D — showing a render instead.',
    specs: 'Specifications',
    material: 'Material',
    dimensions: 'Dimensions',
    mass: 'Mass',
    faces: 'B-Rep faces',
    version: 'Version',
    formats: 'Formats',
    downloads: 'Files',
    preview: '3D preview (GLB)',
    free: 'free',
    pro: 'Pro',
    getPro: 'Available in Monge Pro',
    related: 'More in the library',
  },
  download: {
    title: 'Download Monge',
    lead: 'Monge is in beta. We hand out builds by invitation so we can personally help with your first products.',
    macTitle: 'macOS',
    macText: 'Apple Silicon (M1, M2, M3, M4), macOS 14 or later',
    macCta: 'Request the beta',
    winTitle: 'Windows',
    winText: 'Windows 10 and 11, a GPU with DirectX 12 or Vulkan',
    winCta: 'Notify me at launch',
    soon: 'in development',
    version: 'Version 0.3.0 beta',
    reqTitle: 'Requirements',
    req: ['8 GB RAM, 16 GB recommended', '2 GB of disk space', 'Internet for the library and AI'],
  },
  contact: {
    title: 'Get in touch',
    lead: 'A factory pilot, custom models or a question about Monge — write to us and we will reply within 1–2 business days.',
  },
  privacy: { title: 'Privacy policy' },
  footer: {
    tagline: 'Monge — precise AI-powered CAD for manufacturing. Named after Gaspard Monge, the inventor of descriptive geometry.',
    product: 'Product',
    company: 'Company',
    rights: 'All rights reserved.',
    privacy: 'Privacy',
  },
  notFound: { title: 'Page not found', text: 'Looks like this part is not on the drawing.', cta: 'Home' },
};
