import type { Dict } from '@/lib/i18n';

export const pl: Dict = {
  meta: {
    title: 'Monge — precyzyjny CAD z AI dla producentów urządzeń',
    shortTitle: 'Monge',
    description:
      'Monge tworzy precyzyjne modele 3D urządzeń ze stali nierdzewnej na podstawie wymiarów lub rysunku: stoły, zlewy, regały, komory. Własne jądro B-Rep, konstruktor AI, STEP do produkcji i biblioteka modeli w chmurze.',
  },
  nav: {
    product: 'Program',
    library: 'Biblioteka',
    pricing: 'Cennik',
    download: 'Pobierz',
    contact: 'Kontakt',
    cta: 'Wczesny dostęp',
    menu: 'Menu',
    close: 'Zamknij',
    language: 'Język',
  },
  hero: {
    badge: 'Monge 0.3 — beta dla macOS',
    titleA: 'Od wymiarów',
    titleB: 'do produkcji',
    titleC: 'w kilka minut',
    lead:
      'CAD ze sztuczną inteligencją dla producentów urządzeń gastronomicznych. Opisz stół, zlew lub komorę — Monge zbuduje precyzyjny model i przygotuje pliki dla warsztatu oraz wizualizację dla klienta.',
    primary: 'Uzyskaj wczesny dostęp',
    secondary: 'Zobacz bibliotekę',
    note: 'Zakłady pilotażowe — 3 miesiące za darmo',
    viewerLabel: 'Model na żywo z Monge',
    stats: [
      { value: 'B-Rep', label: 'precyzyjna geometria, nie siatka trójkątów' },
      { value: '~1,5 s', label: 'przebudowa felgi z 530 ścian' },
      { value: 'STEP', label: 'eksport do każdego systemu CAD i CNC' },
    ],
  },
  marquee: ['Stoły produkcyjne', 'Zlewy', 'Regały', 'Wózki', 'Okapy', 'Komory wędzarnicze', 'Komory chłodnicze', 'Części i tuleje', 'Detale toczone'],
  pain: {
    eyebrow: 'Problem',
    title: 'Każde niestandardowe zamówienie to godziny przerysowywania',
    lead:
      'Klient potrzebuje stołu 1730 mm, a nie 1500. Konstruktor znowu otwiera CAD, przesuwa wymiary, przebudowuje rozwinięcia, liczy profile i robi wizualizację do oferty. I tak przy każdym zamówieniu.',
    before: 'Dziś',
    after: 'Z Monge',
    beforeItems: ['Ręczne przerysowywanie wyrobu', 'Rozwinięcia i rozkrój osobno', 'Oferta bez wizualizacji', 'Drogie licencje na każde stanowisko'],
    afterItems: ['Wymiary słowami lub w formularzu', 'Model i pliki przebudowują się same', 'Fotorealistyczny render od razu', 'Abonament w cenie obiadu miesięcznie'],
  },
  how: {
    eyebrow: 'Jak to działa',
    title: 'Cztery kroki od zapytania do warsztatu',
    steps: [
      { title: 'Opisz wyrób', text: 'Wymiarami w formularzu lub zdaniem: „stół przyścienny 1500×600×850, rant 50, półka dolna”.' },
      { title: 'AI buduje model', text: 'Monge składa wyrób na własnym precyzyjnym jądrze: prawdziwe płaszczyzny, walce i zaokrąglenia.' },
      { title: 'Popraw wymiary', text: 'Zmieniasz dowolny parametr — model przebudowuje się w sekundy, historia konstrukcji zostaje.' },
      { title: 'Wyślij do produkcji', text: 'STEP — dla konstruktora i CNC, render — do oferty handlowej.' },
    ],
  },
  features: {
    eyebrow: 'Możliwości',
    title: 'Narzędzie inżyniera, nie zabawka',
    soon: 'w przygotowaniu',
    items: [
      { key: 'kernel', title: 'Własne precyzyjne jądro', text: 'Geometria B-Rep napisana w Rust: płaszczyzny, walce, torusy, NURBS. Bez cudzych bibliotek i licencji.', soon: false },
      { key: 'ai', title: 'Konstruktor AI', text: 'Model powstaje z opisu lub z rysunku: AI steruje Monge i wymiaruje jak inżynier.', soon: false },
      { key: 'history', title: 'Parametry i historia', text: 'Szkic → część → złożenie. Zmienisz wymiar — wszystko się przelicza, błędny krok cofa się sam.', soon: false },
      { key: 'render', title: 'Render do oferty', text: 'Wbudowany render oparty na śledzeniu promieni: obraz do oferty prosto z modelu.', soon: false },
      { key: 'sheet', title: 'Rozwinięcia i rozkrój', text: 'Blacha z giętymi krawędziami, rozwinięcie z K-faktorem Twojej prasy, DXF do lasera, rozkrój profili.', soon: true },
      { key: 'cloud', title: 'Biblioteka w chmurze', text: 'Gotowe wyroby: oglądaj w 3D w przeglądarce i pobieraj pliki do produkcji.', soon: false },
    ],
  },
  showcase: {
    eyebrow: 'Sprawdzone na trudnym',
    title: 'Felga 7J×17 według rysunku fabrycznego',
    text: 'Aby sprawdzić jądro, zbudowaliśmy felgę odlewaną według rysunku producenta: 20 okien, gniazda śrub, zaokrąglenia i wklęsły front. Precyzyjna geometria, 530 ścian, bryła bez jednego błędu.',
    facts: [
      { value: '530', label: 'ścian B-Rep' },
      { value: '20', label: 'okien według rysunku' },
      { value: '0', label: 'błędów topologii' },
    ],
    cta: 'Otwórz model',
  },
  story: {
    eyebrow: 'Dlaczego Monge',
    title: 'Nazwa na cześć Gasparda Monge’a — ojca rysunku technicznego',
    items: [
      { year: 'ok. 300 p.n.e.', name: 'Euklides', text: 'Geometria jako system' },
      { year: '1637', name: 'Kartezjusz', text: 'Współrzędne: kształt staje się liczbą' },
      { year: '1799', name: 'Monge', text: 'Geometria wykreślna — język rysunku' },
      { year: '2026', name: 'Monge', text: 'Rysunek, który buduje AI' },
    ],
  },
  libraryPreview: {
    eyebrow: 'Biblioteka',
    title: 'Modele gotowe do produkcji',
    lead: 'Oglądaj wyroby w 3D w przeglądarce. Pliki produkcyjne są dostępne dla abonentów Monge.',
    cta: 'Cała biblioteka',
  },
  status: {
    eyebrow: 'Uczciwy status',
    title: 'Co już działa i co budujemy',
    doneTitle: 'Działa',
    nextTitle: 'W przygotowaniu',
    done: ['Precyzyjne jądro: obrót, wyciągnięcie, wycięcia, zaokrąglenia', 'Parametryczna historia konstrukcji', 'Złożenia i wiązania części', 'Eksport STEP, STL, 3MF', 'Fotorealistyczny render', 'Sterowanie modelem przez AI'],
    next: ['Blacha i rozwinięcia DXF', 'Ramy z profili zamkniętych', 'Zestawienie materiałów i rozkrój', 'Wersja dla Windows', 'Konfiguracja wyrobu w przeglądarce'],
  },
  pricing: {
    eyebrow: 'Cennik',
    title: 'Prosty abonament bez rocznych umów',
    lead: 'Płacisz co miesiąc i rezygnujesz w dowolnym momencie. Ceny netto.',
    popular: 'Najczęściej wybierany',
    perMonth: '/ mies.',
    plans: [
      { id: 'free', name: 'Start', price: '0 €', desc: 'Poznaj Monge', features: ['Biblioteka i podgląd 3D w przeglądarce', 'Program w trybie podglądu', 'Nowości i aktualizacje'], cta: 'Zacznij za darmo', highlight: false },
      { id: 'pro', name: 'Pro', price: '49 €', desc: 'Dla konstruktora', features: ['Wszystkie szablony wyrobów', 'Konstruktor AI', 'Eksport STEP, STL, 3MF', 'Render do ofert', 'Pliki produkcyjne z biblioteki'], cta: 'Wczesny dostęp', highlight: true },
      { id: 'factory', name: 'Zakład', price: '149 €', desc: 'Dla warsztatu do 3 stanowisk', features: ['Wszystko z Pro', 'Twoje szablony i standardy', 'Logo zakładu w ofertach', 'Wspólna biblioteka warsztatu', 'Wsparcie priorytetowe'], cta: 'Zostań pilotem', highlight: false },
    ],
    custom: { title: 'Modele na zamówienie', text: 'Zamienimy Twoje rysunki w parametryczne szablony Monge. Od 100 € za wyrób.', cta: 'Omów projekt' },
    note: 'Monge jest w wersji beta: abonament na zaproszenie. Zostaw zgłoszenie — zakłady pilotażowe otrzymują 3 miesiące za darmo.',
  },
  faq: {
    eyebrow: 'Pytania',
    title: 'Częste pytania',
    items: [
      { q: 'Czy Monge działa na Windows?', a: 'Obecnie Monge działa na macOS z procesorami Apple Silicon (M1–M4). Wersja dla Windows jest w przygotowaniu — zostaw zgłoszenie, a damy znać o premierze.' },
      { q: 'Czy pliki otworzę w SolidWorks, Fusion lub FreeCAD?', a: 'Monge eksportuje STEP — standardowy format wymiany precyzyjnej geometrii, obsługiwany przez wszystkie główne systemy CAD.' },
      { q: 'Gdzie są przechowywane moje modele?', a: 'Modele powstają i są przechowywane na Twoim komputerze. Do chmury trafia tylko to, co sam opublikujesz w bibliotece.' },
      { q: 'Czy potrzebny jest internet?', a: 'Do pracy z modelami — nie. Internet jest potrzebny do biblioteki, konstruktora AI i weryfikacji abonamentu.' },
      { q: 'Jak zostać zakładem pilotażowym?', a: 'Zostaw zgłoszenie z opisem swoich wyrobów. Przygotujemy szablony Twoich typowych wyrobów i damy 3 miesiące abonamentu za darmo w zamian za opinię.' },
    ],
  },
  cta: {
    title: 'Zróbmy razem Twój pierwszy stół',
    text: 'Opowiedz, co produkujesz. Pokażemy Monge na Twoich wyrobach.',
  },
  form: {
    name: 'Imię',
    email: 'Email',
    company: 'Firma',
    message: 'Co produkujesz?',
    messagePlaceholder: 'Np.: stoły i zlewy z AISI 304, 20–40 zamówień miesięcznie',
    kind: 'Interesuje mnie',
    kinds: { early_access: 'Wczesny dostęp', pilot: 'Pilotaż dla zakładu', custom: 'Modele na zamówienie', other: 'Inne' },
    submit: 'Wyślij zgłoszenie',
    sending: 'Wysyłamy…',
    success: 'Dziękujemy! Zgłoszenie dotarło — odpowiemy w ciągu 1–2 dni roboczych.',
    error: 'Nie udało się wysłać. Spróbuj ponownie za chwilę.',
    consent: 'Wysyłając formularz, akceptujesz',
    privacy: 'politykę prywatności',
  },
  library: {
    title: 'Biblioteka modeli',
    lead: 'Wyroby i części zbudowane w Monge. Obracaj je w 3D w przeglądarce; pliki produkcyjne w abonamencie Pro.',
    all: 'Wszystkie',
    categories: { stainless: 'Stal nierdzewna', precision: 'Części precyzyjne', fasteners: 'Elementy złączne' },
    soonTitle: 'Wkrótce w bibliotece',
    soon: ['Zlewy', 'Regały', 'Wózki', 'Okapy', 'Komory'],
    empty: 'W tej kategorii nie ma jeszcze modeli.',
    open: 'Otwórz',
    formats: 'Formaty',
  },
  item: {
    back: 'Biblioteka',
    viewerHint: 'Obracaj myszą lub palcem, kółko — przybliżenie',
    loading: 'Ładujemy model…',
    noWebgl: 'Przeglądarka nie obsługuje 3D — pokazujemy render.',
    specs: 'Parametry',
    material: 'Materiał',
    dimensions: 'Wymiary',
    mass: 'Masa',
    faces: 'Ściany B-Rep',
    version: 'Wersja',
    formats: 'Formaty',
    downloads: 'Pliki',
    preview: 'Podgląd 3D (GLB)',
    free: 'za darmo',
    pro: 'Pro',
    getPro: 'Dostępne w Monge Pro',
    related: 'Więcej w bibliotece',
  },
  download: {
    title: 'Pobierz Monge',
    lead: 'Monge jest w wersji beta. Udostępniamy wersje na zaproszenie, aby osobiście pomóc przy pierwszych wyrobach.',
    macTitle: 'macOS',
    macText: 'Apple Silicon (M1, M2, M3, M4), macOS 14 lub nowszy',
    macCta: 'Poproś o betę',
    winTitle: 'Windows',
    winText: 'Windows 10 i 11, karta graficzna z DirectX 12 lub Vulkan',
    winCta: 'Powiadom o premierze',
    soon: 'w przygotowaniu',
    version: 'Wersja 0.3.0 beta',
    reqTitle: 'Wymagania',
    req: ['8 GB RAM, zalecane 16 GB', '2 GB miejsca na dysku', 'Internet dla biblioteki i AI'],
  },
  contact: {
    title: 'Skontaktuj się z nami',
    lead: 'Pilotaż dla zakładu, modele na zamówienie lub pytanie o Monge — napisz, odpowiemy w ciągu 1–2 dni roboczych.',
  },
  privacy: { title: 'Polityka prywatności' },
  footer: {
    tagline: 'Monge — precyzyjny CAD ze sztuczną inteligencją dla produkcji. Nazwa na cześć Gasparda Monge’a, twórcy geometrii wykreślnej.',
    product: 'Produkt',
    company: 'Firma',
    rights: 'Wszelkie prawa zastrzeżone.',
    privacy: 'Prywatność',
  },
  notFound: { title: 'Nie znaleziono strony', text: 'Wygląda na to, że tego detalu nie ma na rysunku.', cta: 'Strona główna' },
};
